### ISSUE TITLE
Make app compatible with NC26

### ISSUE THREAD

**Issue by devn1x** [jimmyl0l3c/cfg_share_links#125]
I force installed it in my Nextcloud 26 environment and had no issues so far. So maybe you only have to bump up the version number.

**Comment by solracsf** [comment]
Maybe not fully compatible: https://github.com/jimmyl0l3c/cfg_share_links/issues/143

**Comment by jacotec** [comment]
@solracsf Correct, it breaks NC 26.0.2 and I had to disable the app in my instances therefore :(
