### ISSUE TITLE
Is it possible to use via CLI or API?

### ISSUE THREAD

**Issue by xeruf** [jimmyl0l3c/cfg_share_links#126]
I use `curl` to batch create shares via the OCS Share API: https://docs.nextcloud.com/server/latest/developer_manual/client_apis/OCS/ocs-share-api.html#create-a-new-share

Is there anything similar possible when using this app to batch rename the shares?

**Comment by foxhoundv** [comment]
I am looking for something similar. I use make.com to tie into our companies CRM and based on the sales order number, create a folder in the existing shared folder. I would like to make the newly created folder have a share link automatically.

**Comment by felixschndr** [comment]
Same here, I have not found a way to do this via the API. You can create a new link in the web ui and try to mimic the http request however this requires session cookies…

I'd also love to see the possibility to update/create a share with a custom link

**Comment by devnoname120** [comment]
Ditto, it would be very useful for me for a software that uploads files to Nextcloud via a drag & drop.

**Comment by hugo-akaora** [comment]
Hello, same, would be very useful! Thanks

**Comment by jimmyl0l3c** [comment]
OCS API was added in [v6.0.0](https://github.com/jimmyl0l3c/cfg_share_links/releases/tag/v6.0.0), it is currently not documented, but the endpoints are listed in #267.
