### ISSUE TITLE
App is incompatible with PHP 8.2

### ISSUE THREAD

**Issue by StefanHamminga** [jimmyl0l3c/cfg_share_links#134]
Thank you for this great addon for NC! According to the message in Nextcloud 26 it's not (yet) compatible with PHP 8.2.

Please consider adding support for PHP 8.2 as it's the default in newer Debian releases.

**Comment by jimmyl0l3c** [comment]
Sorry for the wait. The [latest version](https://github.com/jimmyl0l3c/cfg_share_links/releases/tag/v4.0.0) supports PHP 8.2.
