### ISSUE TITLE
App causes 'Error loading file picker template: {error}' when move/copy files in NC 26.0.2

### ISSUE THREAD

**Issue by jacotec** [jimmyl0l3c/cfg_share_links#143]
Unfortunately the app has a serious impact in 26.0.2, causing the mentioned error.
See https://github.com/nextcloud/server/issues/38500

A hotfix would be highly appreciated!

**Comment by jacotec** [comment]
Replacing any existing file is also not possible when the app is active.
"Error loading file exists template"

We really need to have that fixed ...

**Comment by Mer0me** [comment]
I can confirm the bug on 26.0.2.
Waiting for a fix...
