### ISSUE TITLE
Compatibility with NC27 ?

### ISSUE THREAD

**Issue by MilesTEG1** [jimmyl0l3c/cfg_share_links#149]
Hello,
I migrated my Nextcloud instance to the new NC27 version.
Share Links is reported to be incompatible and therefore are not activated:
![image](https://github.com/jimmyl0l3c/cfg_share_links/assets/29298312/fe443209-f711-412b-afae-aadfe11b1b08)

Should I force activation? Is it safe?

And so, would you made compatible this app with NC27?

Thanks

**Comment by jimmyl0l3c** [comment]
Hi, I will look into it over the weekend and I will release a patch resolving compatibility issues.

Thanks for reporting the issue.

**Comment by jimmyl0l3c** [comment]
I deployed new version that is compatible with NC 27 ([Github](https://github.com/jimmyl0l3c/cfg_share_links/releases/tag/v4.1.0), [NC App Store](https://apps.nextcloud.com/apps/cfg_share_links)).
