### ISSUE TITLE
Custom link doesn't work if same as username

### ISSUE THREAD

**Issue by samuel-chaboisseau** [jimmyl0l3c/cfg_share_links#170]
Hi, 
the link doesn't work if it has the same name as a user For example if you use "admin" as a custom link.
With no error, I must unshare and create another share with another name.

Some details : 
Nextcloud 27.1.2
Configurable Share Links : 4.2.0

**Comment by jimmyl0l3c** [comment]
Hi, NC does not allow it, but the app shouldnt let you create such a share, so that has to be adressed.
