### ISSUE TITLE
Make compatible witn NC28

### ISSUE THREAD

**Issue by nursoda** [jimmyl0l3c/cfg_share_links#182]

**Comment by ernolf** [comment]
When I have *`cfg_share_links`* enabled (with *`install_overwrite`*), the download of folders is broken. Instead of a zip file, a "download.php" is offered to download.
So it does definitively not work and breaks other features.

**Comment by ernolf** [comment]
Meanwhile I removed my comment because I thought I was wrong but I have to repeat it, since I could reproduce it on various servers:
I can create configured links, the links are stored and work but as long as the app is activated, the download of folders does not work. It offers a "download.php" instead of a zip file

**Comment by GHBLoos** [comment]
I use this feature a lot. It should be part of Nextcloud in my opinion. I hope this will be compatible soon with NC28, so I can update from NC27 to NC28.

**Comment by ToS0** [comment]
Every page with a customized link ends in a reload loop with the following error in the console:
Content-Security-Policy: The page's settings blocked the loading of a resource at inline ("script-src") Source: event.preventDefault()
Any idea, any support you might need?

**Comment by ToS0** [comment]
Here is a workaround for now, and a patch on its way: https://github.com/nextcloud/server/issues/42200

**Comment by ernolf** [comment]
> Here is a workaround for now, and a patch on its way: [nextcloud/server#42200](https://github.com/nextcloud/server/issues/42200)

This patch did indeed fix it on my various test servers. Has anyone else encountered problems since?

@jimmyl0l3c: so nothing would stand in the way of a release for 28, right?

ernolf

**Comment by ToS0** [comment]
Works with 28.0.2 now -- no workaround needed anymore.

Ticket can be closed

**Comment by GHBLoos** [comment]
That's good news.
I checked my admin - overview page, and there it says that it's not compatible with NC 28.0.2.
![image](https://github.com/jimmyl0l3c/cfg_share_links/assets/16174035/e70f020e-3d48-49f1-9ac3-fcc04a84d4a1)

I suppose it will work. But maybe something should be set to fix this warning.

**Comment by nursoda** [comment]
@GHBLoos As you can see in https://apps.nextcloud.com/apps/cfg_share_links, the maintainer has not released the app for NC 28 yet, so the message "not compatible" is correct.

**Comment by GHBLoos** [comment]
I understand. So this ticket should not yet be closed I quess. I hope the maintainer will create a new release soon.

**Comment by ToS0** [comment]
You are right, the problem is not solved. Only listing folders works, but actually opening contents does still not work. So the workaround from above (Federated Cloud Sharing) is still needed.

**Comment by GHBLoos** [comment]
I would love to update to NC 28, but since I use this app so much, I am still on NC27.
I am curious if the problem is within the app, or the problem is in NC28? In other words, who has to fix the code?

**Comment by jimmyl0l3c** [comment]
Hi, please try the new release ([v5.0.0](https://apps.nextcloud.com/apps/cfg_share_links/releases?platform=28#28)) and let me know if the problem persists.

**Comment by ToS0** [comment]
> Hi, please try the new release ([v5.0.0](https://apps.nextcloud.com/apps/cfg_share_links/releases?platform=28#28)) and let me know if the problem persists.

Hey, great, works now again without the workaround. Thank you!

**Comment by nursoda** [comment]
Thanks for the release. Is there a reason not to set max-version including 29?

**Comment by GHBLoos** [comment]
Thanks you!

**Comment by jimmyl0l3c** [comment]
> Thanks for the release. Is there a reason not to set max-version including 29?

I need to test it properly, but dont have it setup yet. I'll try to release a compatibility patch before NC 29 releases.
