### ISSUE TITLE
When link has a hyphen (-), View or/and Upload isn't possible.

### ISSUE THREAD

**Issue by libnumafly** [jimmyl0l3c/cfg_share_links#223]
Create a shared link containing a hyphen, which cannot be viewed or uploaded when opened.

Below is the log from when the `drop-in` file drop link and attempted to upload a file, but it failed:

```
{
    "reqId": "********",
    "level": 3,
    "time": "2024-05-28T11:54:03+00:00",
    "remoteAddr": "********",
    "user": "--",
    "app": "webdav",
    "method": "PUT",
    "url": "/public.php/dav/files/drop-in/FILENAME",
    "message": "Requested uri (/public.php/dav/files/drop-in/FILENAME) is out of base uri (/public.php/dav/files/drop/)",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36",
    "version": "29.0.1.1",
    "exception": {
        "Exception": "LogicException",
        "Message": "Requested uri (/public.php/dav/files/drop-in/FILENAME) is out of base uri (/public.php/dav/files/drop/)",
        "Code": 0,
        "Trace": [
            {
                "file": "/PATH/TO/WEBROOT/apps/dav/lib/Connector/Sabre/LockPlugin.php",
                "line": 68,
                "function": "getPath",
                "class": "Sabre\\HTTP\\Request",
                "type": "->"
            },
            {
                "file": "/PATH/TO/WEBROOT/3rdparty/sabre/event/lib/WildcardEmitterTrait.php",
                "line": 89,
                "function": "getLock",
                "class": "OCA\\DAV\\Connector\\Sabre\\LockPlugin",
                "type": "->"
            },
            {
                "file": "/PATH/TO/WEBROOT/3rdparty/sabre/dav/lib/DAV/Server.php",
                "line": 456,
                "function": "emit",
                "class": "Sabre\\DAV\\Server",
                "type": "->"
            },
            {
                "file": "/PATH/TO/WEBROOT/3rdparty/sabre/dav/lib/DAV/Server.php",
                "line": 253,
                "function": "invokeMethod",
                "class": "Sabre\\DAV\\Server",
                "type": "->"
            },
            {
                "file": "/PATH/TO/WEBROOT/3rdparty/sabre/dav/lib/DAV/Server.php",
                "line": 321,
                "function": "start",
                "class": "Sabre\\DAV\\Server",
                "type": "->"
            },
            {
                "file": "/PATH/TO/WEBROOT/apps/dav/appinfo/v2/publicremote.php",
                "line": 155,
                "function": "exec",
                "class": "Sabre\\DAV\\Server",
                "type": "->"
            },
            {
                "file": "/PATH/TO/WEBROOT/public.php",
                "line": 101,
                "args": [
                    "/PATH/TO/WEBROOT/apps/dav/appinfo/v2/publicremote.php"
                ],
                "function": "require_once"
            }
        ],
        "File": "/PATH/TO/WEBROOT/3rdparty/sabre/http/lib/Request.php",
        "Line": 184,
        "message": "Requested uri (/public.php/dav/files/drop-in/FILENAME) is out of base uri (/public.php/dav/files/drop/)",
        "exception": {},
        "CustomMessage": "Requested uri (/public.php/dav/files/drop-in/FILENAME) is out of base uri (/public.php/dav/files/drop/)"
    }
}
```

If need more information, please reply.

**Comment by SkullZennith** [comment]
Same issue here. I have an hyphen in my link. Cannot access.

**Comment by Ch3ck3rM0n** [comment]
I have the same issue spoted today in the logs. If I am using "-" in my links, it do not work anymore. In the past it works and now I have to generate new links and inform my customers about it. Its a mess :-/

Please fix it for the future!

**Comment by msm2k11** [comment]
Same problem here after upgrade to NC Hub 8.

**Comment by UserVladimir37** [comment]
In fact, this bug with the "-" symbol in the link name is reproduced for me only for folders that are not at the root, but at least deeper than the root by one folder. For files, links with "-" work at all levels. Most likely, the problem is on the nextcloud side, however, judging by their records, they do not officially support changing links, and also do not use the "-" symbol when generating links. Accordingly, if this bug cannot be circumvented, then it is necessary to prohibit the use of the "-" symbol in the link name when creating it.

**Comment by jimmyl0l3c** [comment]
Hi, this seems to be a problem in Nextcloud. I removed hyphen from the allowed characters in [v5.1.3](https://github.com/jimmyl0l3c/cfg_share_links/releases/tag/v5.1.3)

**Comment by libnumafly** [comment]
> Hi, this seems to be a problem in Nextcloud. I removed hyphen from the allowed characters in [v5.1.3](https://github.com/jimmyl0l3c/cfg_share_links/releases/tag/v5.1.3)

thanks for your work!

**Comment by kottonau** [comment]
What will happen with existing links which contain "-"? We are using this character as string separator in our system and updating would break this functionality. We are still running nc 28.*

Any suggestions are appreciated.

**Comment by jimmyl0l3c** [comment]
> What will happen with existing links which contain "-"? We are using this character as string separator in our system and updating would break this functionality. We are still running nc 28.*
> 
> Any suggestions would be appreciated.

The existing links will continue to work, but you will not be able to create new ones with the hyphen after updating the app to [v5.1.3](https://github.com/jimmyl0l3c/cfg_share_links/releases/tag/v5.1.3) or later.

**Comment by kottonau** [comment]
> > What will happen with existing links which contain "-"? We are using this character as string separator in our system and updating would break this functionality. We are still running nc 28.*
> > Any suggestions would be appreciated.
> 
> The existing links will continue to work, but you will not be able to create new ones with the hyphen after updating the app to [v5.1.3](https://github.com/jimmyl0l3c/cfg_share_links/releases/tag/v5.1.3) or later.

Thank you @jimmyl0l3c.
