### ISSUE TITLE
Cannnot create custom link if password enforcement is active

### ISSUE THREAD

**Issue by ZTHawk** [jimmyl0l3c/cfg_share_links#245]
If password enforcement is active then I cannot create a custom link.
Error I receive:
![grafik](https://github.com/user-attachments/assets/fb951ea7-4102-4b8e-b2d3-2e7bc25cf7d6)

This is how the popup looks like to create a link:
![grafik](https://github.com/user-attachments/assets/e98dc35a-057c-49b2-913a-8745f030faa4)
There is no field to enter a password.

**Comment by jimmyl0l3c** [comment]
Hi, the new version [5.1.2](https://github.com/jimmyl0l3c/cfg_share_links/releases/tag/v5.1.2) fixes the issue, but I am currently having difficulty accessing [apps.nextcloud.com](https://apps.nextcloud.com/) to upload the new release. It may take some time before I release it there.
