### ISSUE TITLE
[Improvements] Add link when pressing enter + Copy link to clipboard

### ISSUE THREAD

**Issue by TtuxX** [jimmyl0l3c/cfg_share_links#25]
Hi there @jimmyl0l3c ! :)

Thank you very much for your great app ! It allows me to save some time and some mouse clicks as I love sharing links that have a meaning.

I would have 3 minor suggestions to make adding a custom link even more flawless:

- Create the link when pressing enter (instead of having to manually click on the '+' button),
- Automatically copy the created link to clipboard (maybe with an option that can be choosed in the app configuration for the default behavior ?)
- Notify the user when the link has been copied to clipboard (like the existing behaviour of the link sharing menu).

Thank you very much in advance for your kind help and for your great app!

Best regards

**Comment by jimmyl0l3c** [comment]
Hi @TtuxX,

thank you for suggestions. The first one (create link by pressing enter) is already implemented and will be available in the next release (during this weekend).
I like the other suggestions and I'll try to implement them soon so its more consistent with the default behavior.

I'm glad you like my app.

**Comment by jimmyl0l3c** [comment]
Automatically copying created link was implemented in [version 1.1.0](https://github.com/jimmyl0l3c/cfg_share_links/releases/tag/v1.1.0).

**Comment by TtuxX** [comment]
Working beautifully, thank you very much !
