### ISSUE TITLE
l10n: Text strings to be corrected

### ISSUE THREAD

**Issue by Valdnet** [jimmyl0l3c/cfg_share_links#31]
- Should be changed to English.

_Reported by the translator at Transifex._

https://github.com/jimmyl0l3c/cfg_share_links/blob/53f910410d348bdb3cecd51d29c75ebb4a25af8c/appinfo/info.xml#L5

- This also needs to be translated into English and added to the translation to Transifex:

https://github.com/jimmyl0l3c/cfg_share_links/blob/53f910410d348bdb3cecd51d29c75ebb4a25af8c/appinfo/info.xml#L7

https://github.com/jimmyl0l3c/cfg_share_links/blob/53f910410d348bdb3cecd51d29c75ebb4a25af8c/appinfo/info.xml#L10-L20

- Officially, there should be no abbreviations in English.

Should be changed:

`Wrong path, file/folder doesn't exist` -> `Wrong path, file/folder does not exist`

https://github.com/jimmyl0l3c/cfg_share_links/blob/53f910410d348bdb3cecd51d29c75ebb4a25af8c/lib/Service/ShareService.php#L126

`Label can't be empty` -> `Label cannot be empty`

https://github.com/jimmyl0l3c/cfg_share_links/blob/9f75f793ef9eb21608ce7c042e14131d007c1575/src/components/AdminSettings.vue#L144

- In the text string below, shouldn't there be `type` instead of `mode`? 

https://github.com/jimmyl0l3c/cfg_share_links/blob/9f75f793ef9eb21608ce7c042e14131d007c1575/src/components/AdminSettings.vue#L18

**Comment by jimmyl0l3c** [comment]
Hopefully everything should be fixed in the latest commit.

**Comment by Valdnet** [comment]
`Nextcloud app that adds the ability to specify share tokens when creating new public links and change tokens of existing links.`

Shouldn't there be: App for Nextcloud?

**Comment by jimmyl0l3c** [comment]
Agreed, it is updated.

**Comment by Valdnet** [comment]
I am closing the issue. If I get an error in any text string, I'll open it again.
Thanks for the corrections 😉.
